### ISSUE TITLE
I wish view the ApiRest

### ISSUE THREAD

**Issue by anderson-as230** [flavioportugal20/cities-api#1]
Você pode postar o link do heroku com tua ApiRest.
You could post link of the heroku with your ApiRest

**Comment by flavioportugal20** [comment]
Boa tarde!
Segue o link do Heroku com a APIRest cities-api
https://cities-api-flavio.herokuapp.com

**Comment by anderson-as230** [comment]
Adicione a sua README.MD
Add to your README.MD
